### ISSUE TITLE
Any master code examples?

### ISSUE THREAD

**Issue by marrobHD** [usedbytes/neopixel_i2c#7]
Are there any master code examples?

**Comment by usedbytes** [comment]
There is this: https://github.com/usedbytes/neopixel_i2c_host (in C)

It was 5 years ago and looks like I didn't write any README or comments... but from what I remember it was monitoring the audio level of the sound card and setting the LEDs based on it.

The actual core driver code is in `neopixel_i2c_host.{c,h}`, which should be pretty self-contained for re-use.
