### ISSUE TITLE
REG_GLB_G, N_LEDS 

### ISSUE THREAD

**Issue by mgeheut** [usedbytes/neopixel_i2c#9]
Hi Brian

I'd be interested in tinkering around with your I2C approach for the WS2812 to drive some LEDs from a ESP32 without having the ESP communicating directly to the LEDs.
While I think I've been following your recommendations, I haven't been able to resolve some issues. The reference for light_ws2812 asks for pointers to the LED array and the number of LEDs in the ws2812_setleds; and while your main.c sketch is providing them, they seem to be undefined.

I'm afraid I might be doing a really stupid mistake (and yes - for the record - I'm fairly new to C). But any help would be highly appreciated.

BR
mgeheut

**Comment by mgeheut** [comment]
Solved - direct lib_reps from GIT did some funny things; adding the libraries directly fixed the issue.

**Comment by usedbytes** [comment]
Glad you got it sorted
